# -*- coding: utf-8 -*-
# Generated by Django 1.9.6 on 2016-05-18 22:41
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Level',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=64, verbose_name='\u0418\u043c\u044f')),
                ('true_photo', models.ImageField(upload_to=b'', verbose_name='\u0422\u0440\u0443')),
                ('fake_photo', models.ImageField(upload_to=b'', verbose_name='\u0424\u044d\u0439\u043a')),
            ],
            options={
                'verbose_name': '\u0423\u0440\u043e\u0432\u0435\u043d\u044c',
                'verbose_name_plural': '\u0423\u0440\u043e\u0432\u043d\u0438',
            },
        ),
    ]
