# -*- coding: utf-8 -*-
# Generated by Django 1.9.6 on 2016-05-18 23:07
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0002_simpleuser'),
    ]

    operations = [
        migrations.AddField(
            model_name='simpleuser',
            name='rating',
            field=models.IntegerField(default=0, verbose_name='Rating'),
        ),
    ]
