# -*- coding: utf-8 -*-
# Generated by Django 1.9.6 on 2016-05-20 13:37
from __future__ import unicode_literals

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0003_simpleuser_rating'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='simpleuser',
            name='id',
        ),
        migrations.AddField(
            model_name='simpleuser',
            name='name',
            field=models.CharField(default=datetime.datetime(2016, 5, 20, 13, 37, 36, 321280, tzinfo=utc), max_length=64, verbose_name='\u0418\u043c\u044f'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='simpleuser',
            name='login',
            field=models.CharField(max_length=64, primary_key=True, serialize=False, verbose_name='\u041b\u043e\u0433\u0438\u043d'),
        ),
    ]
